# Generated by Django 5.1.6 on 2025-02-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploadmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='useruploadmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useruploadmodel',
            name='upload_ip',
        ),
        migrations.RemoveField(
            model_name='useruploadmodel',
            name='upload_time',
        ),
    ]
