# Generated by Django 5.1.6 on 2025-02-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemoModel',
            new_name='DoxModel',
        ),
    ]
